# Generated by Django 3.1.3 on 2021-01-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='due_date',
        ),
    ]
