# Generated by Django 3.1.3 on 2021-01-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_remove_tasklist_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
    ]
