# Generated by Django 3.1.3 on 2021-01-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0003_auto_20210118_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='day',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasklist.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
